# Generated by Django 5.0.6 on 2024-06-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('photo', models.ImageField(blank=True, upload_to='screen/%Y/%m/%d', verbose_name='Photo')),
                ('ready', models.BooleanField(choices=[(False, 'Draft'), (True, 'Published')], default=0, verbose_name='Ready')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='music/None', verbose_name='Track')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album', verbose_name='Album')),
            ],
        ),
    ]
